//! gRPC server for log messages
//!
//! Provides gRPC endpoint for receiving log messages alongside TCP socket.

use std::sync::atomic::AtomicU64;
use std::sync::Arc;
use tokio::sync::mpsc;
use tonic::{Request, Response, Status};

use crate::config::config::Config;
use crate::core::protocol_handlers::handle_grpc_message;
use crate::models::log_entry::LogEntry;
use crate::utils::terminal_ui::print_internal_log;

use microservice_toolbox::network::grpc_server::GrpcServer as ToolboxGrpcServer;

// Add this line - it includes the generated gRPC code
pub mod log_service {
    tonic::include_proto!("logservice");
}

// Import the generated types
use log_service::{
    log_service_server::{LogService, LogServiceServer},
    LogRequest as ProtoLogRequest, // Rename the imported type
    LogResponse,
};

// Include the descriptor set for reflection (generated by build.rs)
pub const LOG_SERVICE_DESCRIPTOR_SET: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/log_service_descriptor.bin"));

/// gRPC server for log messages
pub struct GrpcServer {
    config: Config,
}

//-----------------------------------------------------------------------------------------------

impl GrpcServer {
    /// Create new gRPC server
    pub fn new(config: &Config) -> Self {
        Self {
            config: config.clone(),
        }
    }

    /// Get server name
    pub fn name(&self) -> &str {
        &self.config.name
    }

    //-----------------------------------------------------------------------------------------------

    /// Run the gRPC server
    pub async fn run(
        &self,
        writer_tx: mpsc::Sender<String>,
        sequence_counter: Arc<AtomicU64>,
    ) -> Result<(), Box<dyn std::error::Error>> {
        let addr_str = format!(
            "{host}:{port}",
            host = self.config.host,
            port = self.config.grpc_port
        );

        let service = GrpcLogServiceImpl::new(&self.config, writer_tx, sequence_counter);

        // Use the toolbox wrapper
        let server = ToolboxGrpcServer::new(&addr_str, LOG_SERVICE_DESCRIPTOR_SET);
        server
            .add_service(LogServiceServer::new(service))
            .start()
            .await?;

        Ok(())
    }
}

//-----------------------------------------------------------------------------------------------

/// gRPC service implementation
pub struct GrpcLogServiceImpl {
    writer_tx: mpsc::Sender<String>,
    sequence_counter: Arc<AtomicU64>,
    name: String,
}

//-----------------------------------------------------------------------------------------------

impl GrpcLogServiceImpl {
    /// Create new gRPC service implementation
    pub fn new(
        config: &Config,
        writer_tx: mpsc::Sender<String>,
        sequence_counter: Arc<AtomicU64>,
    ) -> Self {
        Self {
            writer_tx,
            sequence_counter,
            name: config.name.clone(),
        }
    }
}

//-----------------------------------------------------------------------------------------------

#[tonic::async_trait]
impl LogService for GrpcLogServiceImpl {
    /// Handle incoming gRPC log message
    async fn log_message(
        &self,
        request: Request<ProtoLogRequest>, // Use the renamed type
    ) -> Result<Response<LogResponse>, Status> {
        let log_data = request.into_inner();

        // Convert to internal type and handle
        let internal_request = LogEntry::from(log_data); // Use the new name
        match handle_grpc_message(
            internal_request,
            self.writer_tx.clone(),
            self.sequence_counter.clone(),
        )
        .await
        {
            Ok(_) => Ok(Response::new(LogResponse { success: true })),
            Err(e) => {
                print_internal_log(
                    "ERROR",
                    &self.name,
                    "grpc_server.rs",
                    "105",
                    &format!(
                        "{name} - failed to process gRPC message: {e}",
                        name = self.name,
                        e = e
                    ),
                );
                Err(Status::internal(format!(
                    "Failed to process log message: {e}"
                )))
            }
        }
    }
}

//-----------------------------------------------------------------------------------------------

// Conversion from protobuf to internal type
impl From<ProtoLogRequest> for LogEntry {
    // Use the renamed types
    fn from(request: ProtoLogRequest) -> Self {
        Self {
            timestamp: request.timestamp,
            hostname: request.hostname,
            logger_name: request.logger_name,
            level: request.level,
            module: request.module,
            filename: request.filename,
            function_name: request.function_name,
            line_number: request.line_number,
            message: request.message,
            path_name: request.path_name,
            process_id: request.process_id,
            process_name: request.process_name,
            thread_id: request.thread_id,
            thread_name: request.thread_name,
            service_name: request.service_name,
            stack_trace: request.stack_trace,
        }
    }
}
