services:
  # --- Infrastructure ---
  log-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/bastien-antigravity/log-server:${TAG:-latest}
    container_name: log-server
    restart: unless-stopped
    ports:
      - "${LS_IP:-127.0.0.1}:${LS_PORT:-9020}:${LS_PORT:-9020}"
    networks:
      - teleremote-network
    labels: [ com.centurylinklabs.watchtower.enable=true ]

networks:
  teleremote-network:
    name: teleremote-network
    external: true
